import { createZip } from "./zip";

type Subject = { subject?: string; maximum?: number | string | null; obtained?: number | string | null; grade?: string | null };
type Admission = Record<string, unknown> & { applicationNo: string; name: string; phone: string; email?: string | null; course: { title: string }; batch?: { label: string } | null; documents: Array<{ label: string; status: string; fileName: string }> };
const esc = (v: unknown) => String(v ?? "—").replace(/[&<>"']/g, c => ({ "&": "&amp;", "<": "&lt;", ">": "&gt;", '"': "&quot;", "'": "&apos;" })[c]!);
const val = (v: unknown) => v === null || v === undefined || v === "" ? "—" : String(v);
const fmtDate = (v: unknown) => v instanceof Date ? v.toLocaleDateString("en-IN") : val(v);
const yesNo = (v: unknown) => v === true ? "Yes" : v === false ? "No" : "—";
const address = (...parts: unknown[]) => parts.filter(Boolean).join(", ") || "—";
const subjectRows = (v: unknown): Subject[] => Array.isArray(v) ? v as Subject[] : [];
const run = (v: unknown, bold = false, color = "172B3A", size = 20) => `<w:r><w:rPr>${bold ? "<w:b/>" : ""}<w:color w:val="${color}"/><w:sz w:val="${size}"/><w:szCs w:val="${size}"/></w:rPr><w:t xml:space="preserve">${esc(v)}</w:t></w:r>`;
const p = (v: unknown, o: { bold?: boolean; color?: string; size?: number; align?: string; before?: number; after?: number; style?: string; pageBreak?: boolean } = {}) => `<w:p><w:pPr>${o.style ? `<w:pStyle w:val="${o.style}"/>` : ""}${o.align ? `<w:jc w:val="${o.align}"/>` : ""}<w:spacing w:before="${o.before ?? 0}" w:after="${o.after ?? 90}"/>${o.pageBreak ? "<w:pageBreakBefore/>" : ""}</w:pPr>${run(v, o.bold, o.color, o.size)}</w:p>`;

function cell(label: string, value: unknown) {
  return `<w:tc><w:tcPr><w:tcW w:w="4680" w:type="dxa"/><w:shd w:fill="F7FAFC"/><w:tcMar><w:top w:w="110" w:type="dxa"/><w:left w:w="130" w:type="dxa"/><w:bottom w:w="110" w:type="dxa"/><w:right w:w="130" w:type="dxa"/></w:tcMar></w:tcPr><w:p><w:pPr><w:spacing w:after="45"/></w:pPr>${run(label.toUpperCase(), true, "3A718C", 15)}</w:p><w:p>${run(val(value), true, "172B3A", 19)}</w:p></w:tc>`;
}
function table(items: Array<[string, unknown]>) {
  const rows: string[] = [];
  for (let i = 0; i < items.length; i += 2) { const a = items[i], b = items[i + 1] ?? ["", ""]; rows.push(`<w:tr>${cell(a[0], a[1])}${cell(b[0], b[1])}</w:tr>`); }
  return `<w:tbl><w:tblPr><w:tblW w:w="9360" w:type="dxa"/><w:tblLayout w:type="fixed"/><w:tblBorders><w:top w:val="single" w:sz="4" w:color="D8E5EA"/><w:left w:val="single" w:sz="4" w:color="D8E5EA"/><w:bottom w:val="single" w:sz="4" w:color="D8E5EA"/><w:right w:val="single" w:sz="4" w:color="D8E5EA"/><w:insideH w:val="single" w:sz="4" w:color="D8E5EA"/><w:insideV w:val="single" w:sz="4" w:color="D8E5EA"/></w:tblBorders></w:tblPr><w:tblGrid><w:gridCol w:w="4680"/><w:gridCol w:w="4680"/></w:tblGrid>${rows.join("")}</w:tbl>${p("", { after: 60 })}`;
}
const section = (title: string, items: Array<[string, unknown]>, pageBreak = false) => `${p(title, { style: "Heading1", bold: true, color: "075985", size: 25, before: 170, after: 100, pageBreak })}${table(items)}`;

function subjects(title: string, type: unknown, rows: Subject[]) {
  if (!rows.length) return p(`${title} subject-wise details: Not provided`, { color: "5A6B75", size: 18 });
  const grades = type === "GRADES", headings = grades ? ["Subject", "Grade"] : ["Subject", "Maximum marks", "Marks obtained"], widths = grades ? [6500, 2860] : [4560, 2400, 2400];
  const row = (values: unknown[], header = false) => `<w:tr>${values.map((v, i) => `<w:tc><w:tcPr><w:tcW w:w="${widths[i]}" w:type="dxa"/>${header ? '<w:shd w:fill="DFF2F8"/>' : ""}</w:tcPr><w:p><w:pPr><w:spacing w:after="45"/></w:pPr>${run(val(v), header, header ? "075985" : "172B3A", header ? 17 : 18)}</w:p></w:tc>`).join("")}</w:tr>`;
  return `${p(`${title} subject-wise ${grades ? "grades" : "marks"}`, { bold: true, color: "3A718C", size: 19, before: 80, after: 70 })}<w:tbl><w:tblPr><w:tblW w:w="9360" w:type="dxa"/><w:tblLayout w:type="fixed"/><w:tblBorders><w:top w:val="single" w:sz="4" w:color="BFD7E1"/><w:left w:val="single" w:sz="4" w:color="BFD7E1"/><w:bottom w:val="single" w:sz="4" w:color="BFD7E1"/><w:right w:val="single" w:sz="4" w:color="BFD7E1"/><w:insideH w:val="single" w:sz="4" w:color="BFD7E1"/><w:insideV w:val="single" w:sz="4" w:color="BFD7E1"/></w:tblBorders></w:tblPr><w:tblGrid>${widths.map(w => `<w:gridCol w:w="${w}"/>`).join("")}</w:tblGrid>${row(headings, true)}${rows.map(r => row(grades ? [r.subject, r.grade] : [r.subject, r.maximum, r.obtained])).join("")}</w:tbl>`;
}

export function createAdmissionFormDocx(a: Admission) {
  const content = [
    p("DR. VITHALRAO VIKHE PATIL FOUNDATION'S", { bold: true, color: "3A718C", size: 18, align: "center", after: 40 }), p("PARAMEDICAL INSTITUTE", { bold: true, color: "075985", size: 34, align: "center", after: 30 }), p("Opp. Govt. Milk Dairy, MIDC, Ahilyanagar - 414111", { color: "5A6B75", size: 17, align: "center", after: 150 }), p("APPLICATION FOR ADMISSION", { bold: true, color: "075985", size: 28, align: "center", after: 100 }),
    table([["Application number", a.applicationNo], ["Application status", val(a.status).replaceAll("_", " ")], ["Course applied for", a.course.title], ["Batch", a.batch?.label], ["Submitted on", fmtDate(a.submittedAt)], ["Generated on", new Date().toLocaleString("en-IN")]]),
    section("1. Applicant & Identity Details", [["Full name (surname first)", a.name], ["Student mobile", a.phone], ["Email address", a.email], ["Date of birth", fmtDate(a.dateOfBirth)], ["Gender", a.gender], ["Place of birth", a.placeOfBirth], ["Nationality", a.nationality], ["Domicile", val(a.domicile).replaceAll("_", " ")], ["Blood group", a.bloodGroup], ["Aadhaar number", a.aadhaarNumber], ["Caste / category", a.category], ["Contact consent", yesNo(a.contactConsent)]]),
    section("2. Parent Details", [["Father's name", a.fatherName], ["Father's age", a.fatherAge], ["Father's occupation", a.fatherOccupation], ["Father's mobile", a.fatherPhone], ["Father's email", a.fatherEmail], ["Mother's name", a.motherName], ["Mother's age", a.motherAge], ["Mother's mobile", a.motherPhone], ["Mother's email", a.motherEmail], ["Emergency / guardian contact", a.emergencyPhone ?? a.guardianPhone]]),
    section("3. Address Details", [["Present address", address(a.addressLine, a.city, a.district, a.state, a.pinCode)], ["Present residence phone", a.residencePhone], ["Permanent address", address(a.permanentAddressLine, a.permanentCity, a.permanentDistrict, a.permanentState, a.permanentPinCode)], ["Permanent residence phone", a.permanentResidencePhone], ["Permanent same as present", yesNo(a.permanentSameAsPresent)], ["District", a.district]]),
    section("4. Educational Details", [["SSC school", a.schoolName], ["SSC board", a.board], ["SSC year of passing", a.passingYear], ["SSC seat / roll number", a.seatNumber], ["SSC result format", a.sscResultType], ["SSC marks", a.sscResultType === "GRADES" ? "Grade based" : `${val(a.sscMarksObtained)} / ${val(a.sscMaximumMarks)}`], ["SSC percentage", a.percentage == null ? "—" : `${a.percentage}%`], ["Science studied in SSC", yesNo(a.scienceConfirmed)]]),
    subjects("SSC", a.sscResultType, subjectRows(a.sscSubjects)),
    a.hscApplicable ? table([["HSC school / college", a.hscSchoolName], ["HSC board", a.hscBoard], ["HSC year of passing", a.hscPassingYear], ["HSC result format", a.hscResultType], ["HSC marks", a.hscResultType === "GRADES" ? "Grade based" : `${val(a.hscMarksObtained)} / ${val(a.hscMaximumMarks)}`], ["HSC percentage", a.hscPercentage == null ? "—" : `${a.hscPercentage}%`]]) : p("HSC (12th): Not applicable", { bold: true, color: "5A6B75", size: 19, before: 100 }), a.hscApplicable ? subjects("HSC", a.hscResultType, subjectRows(a.hscSubjects)) : "",
    section("5. Payment Details", [["Application fee", `Rs. ${val(a.paymentAmount ?? 50)}`], ["Payment status", val(a.paymentStatus).replaceAll("_", " ")], ["UPI transaction ID", a.paymentTxnRef], ["Payment date", fmtDate(a.paymentDate)], ["Payment proof", a.paymentProofUrl ? "Included in this ZIP" : "Not uploaded"], ["Declaration accepted", yesNo(a.declarationAccepted)]], true),
    p("6. Declaration", { style: "Heading1", bold: true, color: "075985", size: 25, before: 170, after: 90 }), p("I declare that the information and documents supplied in this application are genuine. I have reviewed the course details, fee structure, institute rules and disciplinary requirements. I understand that incorrect, misleading or forged information may result in rejection or discontinuation from the institute.", { color: "263B48", size: 19, after: 170 }), table([["Applicant", a.name], ["Declaration date", fmtDate(a.submittedAt ?? a.updatedAt)], ["Electronic acceptance", a.declarationAccepted ? "Accepted during online submission" : "Not accepted"], ["Application number", a.applicationNo]]),
    section("7. Uploaded Document Checklist", a.documents.length ? a.documents.flatMap((d, i) => [[`${i + 1}. ${d.label}`, d.status], ["Original filename", d.fileName]] as Array<[string, unknown]>) : [["Documents", "No documents uploaded"]]), p("Generated from the applicant's submitted online record. Uploaded files are supplied separately in the accompanying ZIP archive.", { color: "5A6B75", size: 16, align: "center", before: 170, after: 40 }),
  ].join("");
  const document = `<?xml version="1.0" encoding="UTF-8" standalone="yes"?><w:document xmlns:w="http://schemas.openxmlformats.org/wordprocessingml/2006/main"><w:body>${content}<w:sectPr><w:pgSz w:w="12240" w:h="15840"/><w:pgMar w:top="900" w:right="900" w:bottom="900" w:left="900" w:header="400" w:footer="400"/></w:sectPr></w:body></w:document>`;
  const styles = `<?xml version="1.0" encoding="UTF-8"?><w:styles xmlns:w="http://schemas.openxmlformats.org/wordprocessingml/2006/main"><w:docDefaults><w:rPrDefault><w:rPr><w:rFonts w:ascii="Aptos" w:hAnsi="Aptos"/><w:sz w:val="20"/><w:color w:val="172B3A"/></w:rPr></w:rPrDefault></w:docDefaults><w:style w:type="paragraph" w:default="1" w:styleId="Normal"><w:name w:val="Normal"/></w:style><w:style w:type="paragraph" w:styleId="Heading1"><w:name w:val="heading 1"/><w:basedOn w:val="Normal"/><w:next w:val="Normal"/><w:qFormat/><w:pPr><w:keepNext/><w:spacing w:before="170" w:after="100"/></w:pPr><w:rPr><w:b/><w:color w:val="075985"/><w:sz w:val="25"/></w:rPr></w:style></w:styles>`;
  const e = new TextEncoder();
  return createZip([{ name: "[Content_Types].xml", data: e.encode(`<?xml version="1.0"?><Types xmlns="http://schemas.openxmlformats.org/package/2006/content-types"><Default Extension="rels" ContentType="application/vnd.openxmlformats-package.relationships+xml"/><Default Extension="xml" ContentType="application/xml"/><Override PartName="/word/document.xml" ContentType="application/vnd.openxmlformats-officedocument.wordprocessingml.document.main+xml"/><Override PartName="/word/styles.xml" ContentType="application/vnd.openxmlformats-officedocument.wordprocessingml.styles+xml"/></Types>`) }, { name: "_rels/.rels", data: e.encode(`<?xml version="1.0"?><Relationships xmlns="http://schemas.openxmlformats.org/package/2006/relationships"><Relationship Id="rId1" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/officeDocument" Target="word/document.xml"/></Relationships>`) }, { name: "word/document.xml", data: e.encode(document) }, { name: "word/styles.xml", data: e.encode(styles) }, { name: "word/_rels/document.xml.rels", data: e.encode(`<?xml version="1.0"?><Relationships xmlns="http://schemas.openxmlformats.org/package/2006/relationships"><Relationship Id="rId1" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/styles" Target="styles.xml"/></Relationships>`) }]);
}
